//  ***********************************************************************************************
//
//  NSXTool: data reduction for neutron single-crystal diffraction
//
//! @file      autogenerated from core/resources/Resources.h.in
//! @brief     Declares functions that relate to resource files
//!
//! @homepage  ###HOMEPAGE###
//! @license   GNU General Public License v3 or higher (see COPYING)
//! @copyright Institut Laue-Langevin and Forschungszentrum Jülich GmbH 2016-
//! @authors   see CITATION, MAINTAINER
//
//  ***********************************************************************************************

#ifndef CORE_RESOURCES_RESOURCES_H
#define CORE_RESOURCES_RESOURCES_H

#include <yaml-cpp/yaml.h>

namespace nsx {

YAML::Node findResource(const std::pair<std::string, std::string>& resource);

std::set<std::string> getResourcesName(const std::string& resource_type);

} // namespace nsx

#endif // CORE_RESOURCES_RESOURCES_H
