//  ***********************************************************************************************
//
//  NSXTool: data reduction for neutron single-crystal diffraction
//
//! @file      autogenerated from core/resources/Resources.h.in
//! @brief     Defines ###CLASSES###
//!
//! @homepage  ###HOMEPAGE###
//! @license   GNU General Public License v3 or higher (see COPYING)
//! @copyright Institut Laue-Langevin and Forschungszentrum Jülich GmbH 2016-
//! @authors   see CITATION, MAINTAINER
//
//  ***********************************************************************************************

#ifndef RESOURCES_HH
#define RESOURCES_HH

#include <functional>
//@ #include <map>
//@ #include <set>
//@ #include <string>
//@ #include <utility>
//@ #include <vector>

#include <yaml-cpp/yaml.h>

namespace nsx {

using resource_function = std::function<const std::vector<std::string>&()>;

YAML::Node findResource(const std::pair<std::string, std::string>& resource);

void mergeResources(YAML::Node& node1, YAML::Node& node2);

std::set<std::string> getResourcesName(const std::string& resource_type);

} // namespace nsx

#endif // RESOURCES_HH
