//  ***********************************************************************************************
//
//  NSXTool: data reduction for neutron single-crystal diffraction
//
//! @file      autogenerated from core/resources/SingleResource.cpp.in
//! @brief     Defines ###CLASSES###
//!
//! @homepage  ###HOMEPAGE###
//! @license   GNU General Public License v3 or higher (see COPYING)
//! @copyright Institut Laue-Langevin and Forschungszentrum Jülich GmbH 2016-
//! @authors   see CITATION, MAINTAINER
//
//  ***********************************************************************************************

#include "SingleResourceD9.h"

namespace nsx {

const std::vector<std::string>& resource_instruments_D9()
{
    static std::vector<std::string> data = {
        {"---"},
        {"instrument:"},
        {"    name: D9"},
        {"    detector:"},
        {"        name: banana"},
        {"        type: flat"},
        {"        sample_distance:"},
        {"            value: 488.0"},
        {"            units: mm"},
        {"        width:"},
        {"            value: 64.0"},
        {"            units: mm"},
        {"        height:"},
        {"           value: 64.0"},
        {"           units: mm"},
        {"        nrows: 32"},
        {"        ncols: 32"},
        {"        row_min: 0"},
        {"        col_min: 0"},
        {"        data_ordering: BottomRightColMajor"},
        {"        goniometer:"},
        {"            name: detector-gonio"},
        {"            axis:"},
        {"                - name: 2theta(gamma)"},
        {"                  type: rotation"},
        {"                  id: 1"},
        {"                  direction: [0.0,0.0,1.0]"},
        {"                  clockwise: true"},
        {"                  physical: true"},
        {"    sample:"},
        {"        name: sample"},
        {"        goniometer:"},
        {"            name: sample-gonio"},
        {"            axis:"},
        {"                - name: omega"},
        {"                  type: rotation"},
        {"                  id: 2"},
        {"                  direction: [0.0,0.0,1.0]"},
        {"                  clockwise: true"},
        {"                  physical: true"},
        {""},
        {"                - name: chi"},
        {"                  type: rotation"},
        {"                  id: 3"},
        {"                  direction: [0.0,1.0,0.0]"},
        {"                  clockwise: false"},
        {"                  physical: true"},
        {""},
        {"                - name: phi"},
        {"                  type: rotation"},
        {"                  id: 4"},
        {"                  direction: [0.0,0.0,1.0]"},
        {"                  clockwise: true"},
        {"                  physical: true"},
        {"    source:"},
        {"        name: monochromatic source"},
        {"        monochromator:"},
        {"            name: Cu(220)"},
        {"            width:"},
        {"                value: 60.0"},
        {"                units: mm"},
        {"            height:"},
        {"                value: 80.0"},
        {"                units: mm"},
        {"            wavelength:"},
        {"                value: 0.8409"},
        {"                units: ang"},
        {"            fwhm:"},
        {"                value: 0.00901"},
        {"                units: ang"},
        {"..."},
    };
    return data;
}

} // namespace nsx
