set(CPACK_GENERATOR "RPM")

find_program(RPMBUILD_CMD rpmbuild)

if (RPMBUILD_CMD)
    
  execute_process(COMMAND arch OUTPUT_VARIABLE CPACK_RPM_PACKAGE_ARCHITECTURE OUTPUT_STRIP_TRAILING_WHITESPACE)
  
else(RPMBUILD_CMD)

  set(CPACK_RPM_PACKAGE_ARCHITECTURE "${CMAKE_SYSTEM_PROCESSOR}")

endif(RPMBUILD_CMD)

set(CPACK_RPM_PACKAGE_LICENSE GPLv3+)
set(CPACK_RPM_PACKAGE_RELEASE 1)
set(CPACK_RPM_PACKAGE_GROUP Applications/Science)

set(CPACK_RPM_PACKAGE_URL ${CPACK_PACKAGE_URL})

