if(APPLE AND ENABLE_CPACK)
    set(BUNDLE BUNDLE)
    set(NSXQT_INSTALL_DIR ${NSXTOOL_BUNDLE_DIR})
    set_source_files_properties(${CMAKE_SOURCE_DIR}/apps/nsxqt/resources/nsxtool.icns PROPERTIES MACOSX_PACKAGE_LOCATION Resources)
    set(EXECUTABLE_OPTIONS MACOSX_BUNDLE)
    set(NSX_LIB_TYPE SHARED)
elseif(WIN32)
    set(BUNDLE)
    set(NSXQT_INSTALL_DIR bin)
    set(EXECUTABLE_OPTIONS WIN32)
    set(NSX_LIB_TYPE STATIC)
else()
    set(BUNDLE)
    set(NSXQT_INSTALL_DIR bin)
    set(EXECUTABLE_OPTIONS)
    set(NSX_LIB_TYPE SHARED)
endif()

if (NSX_BUILD_STATIC)
    set(NSX_LIB_TYPE STATIC)
endif()

set(NSX_LIBRARY nsx)
set(NSXQT_EXECUTABLE nsxqt)

