if(APPLE)
    set(NSXQT_LINK_FLAGS "-Wl,-rpath,@loader_path/../../core/")
elseif(UNIX)
    set(NSXQT_LINK_FLAGS "-Wl,-rpath,@loader_path/../lib")
else(WIN32)
    set(NSXQT_LINK_FLAGS "/ENTRY:mainCRTStartup")
endif()
